// Code generated by go-swagger; DO NOT EDIT.

package runnable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRunnableParams creates a new GetRunnableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRunnableParams() *GetRunnableParams {
	return &GetRunnableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRunnableParamsWithTimeout creates a new GetRunnableParams object
// with the ability to set a timeout on a request.
func NewGetRunnableParamsWithTimeout(timeout time.Duration) *GetRunnableParams {
	return &GetRunnableParams{
		timeout: timeout,
	}
}

// NewGetRunnableParamsWithContext creates a new GetRunnableParams object
// with the ability to set a context for a request.
func NewGetRunnableParamsWithContext(ctx context.Context) *GetRunnableParams {
	return &GetRunnableParams{
		Context: ctx,
	}
}

// NewGetRunnableParamsWithHTTPClient creates a new GetRunnableParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRunnableParamsWithHTTPClient(client *http.Client) *GetRunnableParams {
	return &GetRunnableParams{
		HTTPClient: client,
	}
}

/* GetRunnableParams contains all the parameters to send to the API endpoint
   for the get runnable operation.

   Typically these are written to a http.Request.
*/
type GetRunnableParams struct {

	/* RunnableNameOrID.

	   Runnable name or id
	*/
	RunnableNameOrID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get runnable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRunnableParams) WithDefaults() *GetRunnableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get runnable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRunnableParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get runnable params
func (o *GetRunnableParams) WithTimeout(timeout time.Duration) *GetRunnableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get runnable params
func (o *GetRunnableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get runnable params
func (o *GetRunnableParams) WithContext(ctx context.Context) *GetRunnableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get runnable params
func (o *GetRunnableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get runnable params
func (o *GetRunnableParams) WithHTTPClient(client *http.Client) *GetRunnableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get runnable params
func (o *GetRunnableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRunnableNameOrID adds the runnableNameOrID to the get runnable params
func (o *GetRunnableParams) WithRunnableNameOrID(runnableNameOrID string) *GetRunnableParams {
	o.SetRunnableNameOrID(runnableNameOrID)
	return o
}

// SetRunnableNameOrID adds the runnableNameOrId to the get runnable params
func (o *GetRunnableParams) SetRunnableNameOrID(runnableNameOrID string) {
	o.RunnableNameOrID = runnableNameOrID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRunnableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param runnableNameOrId
	if err := r.SetPathParam("runnableNameOrId", o.RunnableNameOrID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
