// Code generated by go-swagger; DO NOT EDIT.

package runnable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListRunnablesParams creates a new ListRunnablesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListRunnablesParams() *ListRunnablesParams {
	return &ListRunnablesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListRunnablesParamsWithTimeout creates a new ListRunnablesParams object
// with the ability to set a timeout on a request.
func NewListRunnablesParamsWithTimeout(timeout time.Duration) *ListRunnablesParams {
	return &ListRunnablesParams{
		timeout: timeout,
	}
}

// NewListRunnablesParamsWithContext creates a new ListRunnablesParams object
// with the ability to set a context for a request.
func NewListRunnablesParamsWithContext(ctx context.Context) *ListRunnablesParams {
	return &ListRunnablesParams{
		Context: ctx,
	}
}

// NewListRunnablesParamsWithHTTPClient creates a new ListRunnablesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListRunnablesParamsWithHTTPClient(client *http.Client) *ListRunnablesParams {
	return &ListRunnablesParams{
		HTTPClient: client,
	}
}

/* ListRunnablesParams contains all the parameters to send to the API endpoint
   for the list runnables operation.

   Typically these are written to a http.Request.
*/
type ListRunnablesParams struct {

	/* ID.

	   The runnable's id
	*/
	ID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list runnables params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListRunnablesParams) WithDefaults() *ListRunnablesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list runnables params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListRunnablesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list runnables params
func (o *ListRunnablesParams) WithTimeout(timeout time.Duration) *ListRunnablesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list runnables params
func (o *ListRunnablesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list runnables params
func (o *ListRunnablesParams) WithContext(ctx context.Context) *ListRunnablesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list runnables params
func (o *ListRunnablesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list runnables params
func (o *ListRunnablesParams) WithHTTPClient(client *http.Client) *ListRunnablesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list runnables params
func (o *ListRunnablesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list runnables params
func (o *ListRunnablesParams) WithID(id *string) *ListRunnablesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list runnables params
func (o *ListRunnablesParams) SetID(id *string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ListRunnablesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
