// Code generated by go-swagger; DO NOT EDIT.

package runnable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fuseml/fuseml-core/pkg/models"
)

// NewRegisterRunnableParams creates a new RegisterRunnableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRegisterRunnableParams() *RegisterRunnableParams {
	return &RegisterRunnableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRegisterRunnableParamsWithTimeout creates a new RegisterRunnableParams object
// with the ability to set a timeout on a request.
func NewRegisterRunnableParamsWithTimeout(timeout time.Duration) *RegisterRunnableParams {
	return &RegisterRunnableParams{
		timeout: timeout,
	}
}

// NewRegisterRunnableParamsWithContext creates a new RegisterRunnableParams object
// with the ability to set a context for a request.
func NewRegisterRunnableParamsWithContext(ctx context.Context) *RegisterRunnableParams {
	return &RegisterRunnableParams{
		Context: ctx,
	}
}

// NewRegisterRunnableParamsWithHTTPClient creates a new RegisterRunnableParams object
// with the ability to set a custom HTTPClient for a request.
func NewRegisterRunnableParamsWithHTTPClient(client *http.Client) *RegisterRunnableParams {
	return &RegisterRunnableParams{
		HTTPClient: client,
	}
}

/* RegisterRunnableParams contains all the parameters to send to the API endpoint
   for the register runnable operation.

   Typically these are written to a http.Request.
*/
type RegisterRunnableParams struct {

	/* Runnable.

	   Runnable descriptor
	*/
	Runnable *models.RunnableReq

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the register runnable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterRunnableParams) WithDefaults() *RegisterRunnableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the register runnable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterRunnableParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the register runnable params
func (o *RegisterRunnableParams) WithTimeout(timeout time.Duration) *RegisterRunnableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the register runnable params
func (o *RegisterRunnableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the register runnable params
func (o *RegisterRunnableParams) WithContext(ctx context.Context) *RegisterRunnableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the register runnable params
func (o *RegisterRunnableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the register runnable params
func (o *RegisterRunnableParams) WithHTTPClient(client *http.Client) *RegisterRunnableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the register runnable params
func (o *RegisterRunnableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRunnable adds the runnable to the register runnable params
func (o *RegisterRunnableParams) WithRunnable(runnable *models.RunnableReq) *RegisterRunnableParams {
	o.SetRunnable(runnable)
	return o
}

// SetRunnable adds the runnable to the register runnable params
func (o *RegisterRunnableParams) SetRunnable(runnable *models.RunnableReq) {
	o.Runnable = runnable
}

// WriteToRequest writes these params to a swagger request
func (o *RegisterRunnableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Runnable != nil {
		if err := r.SetBodyParam(o.Runnable); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
