// Code generated by go-swagger; DO NOT EDIT.

package runnable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fuseml/fuseml-core/pkg/models"
)

// RegisterRunnableReader is a Reader for the RegisterRunnable structure.
type RegisterRunnableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RegisterRunnableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewRegisterRunnableCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRegisterRunnableBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRegisterRunnableCreated creates a RegisterRunnableCreated with default headers values
func NewRegisterRunnableCreated() *RegisterRunnableCreated {
	return &RegisterRunnableCreated{}
}

/* RegisterRunnableCreated describes a response with status code 201, with default header values.

Runnable registered
*/
type RegisterRunnableCreated struct {
	Payload *models.Runnable
}

func (o *RegisterRunnableCreated) Error() string {
	return fmt.Sprintf("[POST /runnables][%d] registerRunnableCreated  %+v", 201, o.Payload)
}
func (o *RegisterRunnableCreated) GetPayload() *models.Runnable {
	return o.Payload
}

func (o *RegisterRunnableCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Runnable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRegisterRunnableBadRequest creates a RegisterRunnableBadRequest with default headers values
func NewRegisterRunnableBadRequest() *RegisterRunnableBadRequest {
	return &RegisterRunnableBadRequest{}
}

/* RegisterRunnableBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RegisterRunnableBadRequest struct {
}

func (o *RegisterRunnableBadRequest) Error() string {
	return fmt.Sprintf("[POST /runnables][%d] registerRunnableBadRequest ", 400)
}

func (o *RegisterRunnableBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
