// Code generated by go-swagger; DO NOT EDIT.

// Package api Fuseml
//
//  FuseML service API
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package api
