// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "FuseML service API",
    "title": "Fuseml",
    "version": "1.0.0"
  },
  "host": "localhost",
  "basePath": "/api",
  "paths": {
    "/runnables": {
      "get": {
        "description": "Get information about runnables currently registered in the FuseML runnable store",
        "tags": [
          "runnable"
        ],
        "summary": "Retrieve runnable information",
        "operationId": "listRunnables",
        "parameters": [
          {
            "type": "string",
            "description": "The runnable's id",
            "name": "id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Return all registered runnables matching the query",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Runnable"
              }
            }
          }
        }
      },
      "post": {
        "description": "Register a runnable with the FuseML runnable store",
        "tags": [
          "runnable"
        ],
        "summary": "Register runnable",
        "operationId": "registerRunnable",
        "parameters": [
          {
            "description": "Runnable descriptor",
            "name": "runnable",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RunnableReq"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Runnable registered",
            "schema": {
              "$ref": "#/definitions/Runnable"
            }
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/runnables/{runnableNameOrId}": {
      "get": {
        "description": "Lookup information about a runnable in the FuseML store",
        "tags": [
          "runnable"
        ],
        "summary": "Get information about a runnable",
        "operationId": "getRunnable",
        "parameters": [
          {
            "type": "string",
            "description": "Runnable name or id",
            "name": "runnableNameOrId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Return matching runnable resource",
            "schema": {
              "$ref": "#/definitions/Runnable"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Runnable Not Found"
          }
        }
      }
    }
  },
  "definitions": {
    "InputParameter": {
      "type": "object",
      "properties": {
        "datatype": {
          "description": "Parameter data type",
          "type": "string"
        },
        "default": {
          "description": "Default value",
          "type": "string"
        },
        "optional": {
          "description": "Optional parameter",
          "type": "boolean",
          "default": true
        }
      }
    },
    "Runnable": {
      "type": "object",
      "properties": {
        "created": {
          "description": "The runnable's creation time",
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "description": "The ID of the runnable",
          "type": "string",
          "format": "uuid"
        },
        "image": {
          "description": "The OCI container image associated with the runnable",
          "$ref": "#/definitions/RunnableImage"
        },
        "inputs": {
          "description": "List of inputs (artifacts, values etc.) accepted by this runnable",
          "type": "array",
          "items": {
            "$ref": "#/definitions/RunnableInput"
          }
        },
        "kind": {
          "description": "The kind of runnable (builder, trainer, predictor etc.)",
          "type": "string"
        },
        "labels": {
          "description": "Labels associated with the runnable",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "description": "The name of the runnable",
          "type": "string"
        },
        "outputs": {
          "description": "List of outputs (artifacts, values etc.) generated by this runnable",
          "type": "array",
          "items": {
            "$ref": "#/definitions/RunnableOutput"
          }
        }
      }
    },
    "RunnableImage": {
      "type": "object",
      "properties": {
        "registryUrl": {
          "description": "The URL for the external registry where the image is stored (empty for internal images)",
          "type": "string"
        },
        "repository": {
          "description": "The image repository",
          "type": "string"
        },
        "tag": {
          "description": "The image tag",
          "type": "string"
        }
      }
    },
    "RunnableInput": {
      "type": "object",
      "properties": {
        "kind": {
          "description": "Kind of input (e.g. runnable, dataset, model, parameter etc.)",
          "type": "string"
        },
        "name": {
          "description": "Input name",
          "type": "string"
        },
        "parameter": {
          "description": "Parameter description",
          "$ref": "#/definitions/InputParameter"
        },
        "runnable": {
          "description": "Runnable reference",
          "$ref": "#/definitions/RunnableRef"
        }
      }
    },
    "RunnableOutput": {
      "type": "object",
      "properties": {
        "kind": {
          "description": "Kind of input (e.g. runnable, dataset, model, metadata etc.)",
          "type": "string"
        },
        "metadata": {
          "description": "Metadata description",
          "$ref": "#/definitions/InputParameter"
        },
        "name": {
          "description": "Input name",
          "type": "string"
        },
        "runnable": {
          "description": "Runnable reference",
          "$ref": "#/definitions/RunnableRef"
        }
      }
    },
    "RunnableRef": {
      "type": "object",
      "properties": {
        "kind": {
          "description": "Runnable kind",
          "type": "string"
        },
        "labels": {
          "description": "Runnable labels",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "description": "Runnable name",
          "type": "string"
        }
      }
    },
    "RunnableReq": {
      "type": "object",
      "properties": {
        "image": {
          "description": "The OCI container image associated with the runnable",
          "$ref": "#/definitions/RunnableImage"
        },
        "inputs": {
          "description": "List of inputs (artifacts, values etc.) accepted by this runnable",
          "type": "array",
          "items": {
            "$ref": "#/definitions/RunnableInput"
          }
        },
        "kind": {
          "description": "The kind of runnable (builder, trainer, predictor etc.)",
          "type": "string"
        },
        "labels": {
          "description": "Labels associated with the runnable",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "description": "The name of the runnable",
          "type": "string"
        },
        "outputs": {
          "description": "List of outputs (artifacts, values etc.) generated by this runnable",
          "type": "array",
          "items": {
            "$ref": "#/definitions/RunnableOutput"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "FuseML service API",
    "title": "Fuseml",
    "version": "1.0.0"
  },
  "host": "localhost",
  "basePath": "/api",
  "paths": {
    "/runnables": {
      "get": {
        "description": "Get information about runnables currently registered in the FuseML runnable store",
        "tags": [
          "runnable"
        ],
        "summary": "Retrieve runnable information",
        "operationId": "listRunnables",
        "parameters": [
          {
            "type": "string",
            "description": "The runnable's id",
            "name": "id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Return all registered runnables matching the query",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Runnable"
              }
            }
          }
        }
      },
      "post": {
        "description": "Register a runnable with the FuseML runnable store",
        "tags": [
          "runnable"
        ],
        "summary": "Register runnable",
        "operationId": "registerRunnable",
        "parameters": [
          {
            "description": "Runnable descriptor",
            "name": "runnable",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RunnableReq"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Runnable registered",
            "schema": {
              "$ref": "#/definitions/Runnable"
            }
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/runnables/{runnableNameOrId}": {
      "get": {
        "description": "Lookup information about a runnable in the FuseML store",
        "tags": [
          "runnable"
        ],
        "summary": "Get information about a runnable",
        "operationId": "getRunnable",
        "parameters": [
          {
            "type": "string",
            "description": "Runnable name or id",
            "name": "runnableNameOrId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Return matching runnable resource",
            "schema": {
              "$ref": "#/definitions/Runnable"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Runnable Not Found"
          }
        }
      }
    }
  },
  "definitions": {
    "InputParameter": {
      "type": "object",
      "properties": {
        "datatype": {
          "description": "Parameter data type",
          "type": "string"
        },
        "default": {
          "description": "Default value",
          "type": "string"
        },
        "optional": {
          "description": "Optional parameter",
          "type": "boolean",
          "default": true
        }
      }
    },
    "Runnable": {
      "type": "object",
      "properties": {
        "created": {
          "description": "The runnable's creation time",
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "description": "The ID of the runnable",
          "type": "string",
          "format": "uuid"
        },
        "image": {
          "description": "The OCI container image associated with the runnable",
          "$ref": "#/definitions/RunnableImage"
        },
        "inputs": {
          "description": "List of inputs (artifacts, values etc.) accepted by this runnable",
          "type": "array",
          "items": {
            "$ref": "#/definitions/RunnableInput"
          }
        },
        "kind": {
          "description": "The kind of runnable (builder, trainer, predictor etc.)",
          "type": "string"
        },
        "labels": {
          "description": "Labels associated with the runnable",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "description": "The name of the runnable",
          "type": "string"
        },
        "outputs": {
          "description": "List of outputs (artifacts, values etc.) generated by this runnable",
          "type": "array",
          "items": {
            "$ref": "#/definitions/RunnableOutput"
          }
        }
      }
    },
    "RunnableImage": {
      "type": "object",
      "properties": {
        "registryUrl": {
          "description": "The URL for the external registry where the image is stored (empty for internal images)",
          "type": "string"
        },
        "repository": {
          "description": "The image repository",
          "type": "string"
        },
        "tag": {
          "description": "The image tag",
          "type": "string"
        }
      }
    },
    "RunnableInput": {
      "type": "object",
      "properties": {
        "kind": {
          "description": "Kind of input (e.g. runnable, dataset, model, parameter etc.)",
          "type": "string"
        },
        "name": {
          "description": "Input name",
          "type": "string"
        },
        "parameter": {
          "description": "Parameter description",
          "$ref": "#/definitions/InputParameter"
        },
        "runnable": {
          "description": "Runnable reference",
          "$ref": "#/definitions/RunnableRef"
        }
      }
    },
    "RunnableOutput": {
      "type": "object",
      "properties": {
        "kind": {
          "description": "Kind of input (e.g. runnable, dataset, model, metadata etc.)",
          "type": "string"
        },
        "metadata": {
          "description": "Metadata description",
          "$ref": "#/definitions/InputParameter"
        },
        "name": {
          "description": "Input name",
          "type": "string"
        },
        "runnable": {
          "description": "Runnable reference",
          "$ref": "#/definitions/RunnableRef"
        }
      }
    },
    "RunnableRef": {
      "type": "object",
      "properties": {
        "kind": {
          "description": "Runnable kind",
          "type": "string"
        },
        "labels": {
          "description": "Runnable labels",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "description": "Runnable name",
          "type": "string"
        }
      }
    },
    "RunnableReq": {
      "type": "object",
      "properties": {
        "image": {
          "description": "The OCI container image associated with the runnable",
          "$ref": "#/definitions/RunnableImage"
        },
        "inputs": {
          "description": "List of inputs (artifacts, values etc.) accepted by this runnable",
          "type": "array",
          "items": {
            "$ref": "#/definitions/RunnableInput"
          }
        },
        "kind": {
          "description": "The kind of runnable (builder, trainer, predictor etc.)",
          "type": "string"
        },
        "labels": {
          "description": "Labels associated with the runnable",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "description": "The name of the runnable",
          "type": "string"
        },
        "outputs": {
          "description": "List of outputs (artifacts, values etc.) generated by this runnable",
          "type": "array",
          "items": {
            "$ref": "#/definitions/RunnableOutput"
          }
        }
      }
    }
  }
}`))
}
