---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone
  namespace: fuseml-workloads
spec:
  workspaces:
    - name: source
  resources:
    inputs:
      - name: source-repo
        type: git
        targetPath: source
  steps:
    - name: stage
      image: lachlanevenson/k8s-kubectl
      workingDir: "/workspace/source"
      script: |
        pwd
        ls -la
    - name: prepare
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.22.0
      workingDir: "/workspace/source"
      script: |
        basename `git config --get remote.origin.url` .git | tee .fuseml/_project
        basename $(dirname `git config --get remote.origin.url`) | tee .fuseml/_org
