// Code generated by go-swagger; DO NOT EDIT.

package runnable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetRunnableParams creates a new GetRunnableParams object
//
// There are no default values defined in the spec.
func NewGetRunnableParams() GetRunnableParams {

	return GetRunnableParams{}
}

// GetRunnableParams contains all the bound params for the get runnable operation
// typically these are obtained from a http.Request
//
// swagger:parameters getRunnable
type GetRunnableParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Runnable name or id
	  Required: true
	  In: path
	*/
	RunnableNameOrID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetRunnableParams() beforehand.
func (o *GetRunnableParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRunnableNameOrID, rhkRunnableNameOrID, _ := route.Params.GetOK("runnableNameOrId")
	if err := o.bindRunnableNameOrID(rRunnableNameOrID, rhkRunnableNameOrID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRunnableNameOrID binds and validates parameter RunnableNameOrID from path.
func (o *GetRunnableParams) bindRunnableNameOrID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.RunnableNameOrID = raw

	return nil
}
