// Code generated by go-swagger; DO NOT EDIT.

package runnable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRunnableHandlerFunc turns a function with the right signature into a get runnable handler
type GetRunnableHandlerFunc func(GetRunnableParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRunnableHandlerFunc) Handle(params GetRunnableParams) middleware.Responder {
	return fn(params)
}

// GetRunnableHandler interface for that can handle valid get runnable params
type GetRunnableHandler interface {
	Handle(GetRunnableParams) middleware.Responder
}

// NewGetRunnable creates a new http.Handler for the get runnable operation
func NewGetRunnable(ctx *middleware.Context, handler GetRunnableHandler) *GetRunnable {
	return &GetRunnable{Context: ctx, Handler: handler}
}

/* GetRunnable swagger:route GET /runnables/{runnableNameOrId} runnable getRunnable

Get information about a runnable

Lookup information about a runnable in the FuseML store

*/
type GetRunnable struct {
	Context *middleware.Context
	Handler GetRunnableHandler
}

func (o *GetRunnable) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetRunnableParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
