// Code generated by go-swagger; DO NOT EDIT.

package runnable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/fuseml/fuseml/core/pkg/models"
)

// GetRunnableOKCode is the HTTP code returned for type GetRunnableOK
const GetRunnableOKCode int = 200

/*GetRunnableOK Return matching runnable resource

swagger:response getRunnableOK
*/
type GetRunnableOK struct {

	/*
	  In: Body
	*/
	Payload *models.Runnable `json:"body,omitempty"`
}

// NewGetRunnableOK creates GetRunnableOK with default headers values
func NewGetRunnableOK() *GetRunnableOK {

	return &GetRunnableOK{}
}

// WithPayload adds the payload to the get runnable o k response
func (o *GetRunnableOK) WithPayload(payload *models.Runnable) *GetRunnableOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get runnable o k response
func (o *GetRunnableOK) SetPayload(payload *models.Runnable) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRunnableOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRunnableBadRequestCode is the HTTP code returned for type GetRunnableBadRequest
const GetRunnableBadRequestCode int = 400

/*GetRunnableBadRequest Bad Request

swagger:response getRunnableBadRequest
*/
type GetRunnableBadRequest struct {
}

// NewGetRunnableBadRequest creates GetRunnableBadRequest with default headers values
func NewGetRunnableBadRequest() *GetRunnableBadRequest {

	return &GetRunnableBadRequest{}
}

// WriteResponse to the client
func (o *GetRunnableBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetRunnableNotFoundCode is the HTTP code returned for type GetRunnableNotFound
const GetRunnableNotFoundCode int = 404

/*GetRunnableNotFound Runnable Not Found

swagger:response getRunnableNotFound
*/
type GetRunnableNotFound struct {
}

// NewGetRunnableNotFound creates GetRunnableNotFound with default headers values
func NewGetRunnableNotFound() *GetRunnableNotFound {

	return &GetRunnableNotFound{}
}

// WriteResponse to the client
func (o *GetRunnableNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
