// Code generated by go-swagger; DO NOT EDIT.

package runnable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/fuseml/fuseml-core/pkg/models"
)

// ListRunnablesOKCode is the HTTP code returned for type ListRunnablesOK
const ListRunnablesOKCode int = 200

/*ListRunnablesOK Return all registered runnables matching the query

swagger:response listRunnablesOK
*/
type ListRunnablesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Runnable `json:"body,omitempty"`
}

// NewListRunnablesOK creates ListRunnablesOK with default headers values
func NewListRunnablesOK() *ListRunnablesOK {

	return &ListRunnablesOK{}
}

// WithPayload adds the payload to the list runnables o k response
func (o *ListRunnablesOK) WithPayload(payload []*models.Runnable) *ListRunnablesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list runnables o k response
func (o *ListRunnablesOK) SetPayload(payload []*models.Runnable) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRunnablesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Runnable, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
