// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InputParameter input parameter
//
// swagger:model InputParameter
type InputParameter struct {

	// Parameter data type
	Datatype string `json:"datatype,omitempty"`

	// Default value
	Default string `json:"default,omitempty"`

	// Optional parameter
	Optional *bool `json:"optional,omitempty"`
}

// Validate validates this input parameter
func (m *InputParameter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this input parameter based on context it is used
func (m *InputParameter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InputParameter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InputParameter) UnmarshalBinary(b []byte) error {
	var res InputParameter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
