// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RunnableImage runnable image
//
// swagger:model RunnableImage
type RunnableImage struct {

	// The URL for the external registry where the image is stored (empty for internal images)
	RegistryURL string `json:"registryUrl,omitempty"`

	// The image repository
	Repository string `json:"repository,omitempty"`

	// The image tag
	Tag string `json:"tag,omitempty"`
}

// Validate validates this runnable image
func (m *RunnableImage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this runnable image based on context it is used
func (m *RunnableImage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RunnableImage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RunnableImage) UnmarshalBinary(b []byte) error {
	var res RunnableImage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
