// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RunnableRef runnable ref
//
// swagger:model RunnableRef
type RunnableRef struct {

	// Runnable kind
	Kind string `json:"kind,omitempty"`

	// Runnable labels
	Labels []string `json:"labels"`

	// Runnable name
	Name string `json:"name,omitempty"`
}

// Validate validates this runnable ref
func (m *RunnableRef) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this runnable ref based on context it is used
func (m *RunnableRef) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RunnableRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RunnableRef) UnmarshalBinary(b []byte) error {
	var res RunnableRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
