// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RunnableOutput runnable output
//
// swagger:model RunnableOutput
type RunnableOutput struct {

	// Kind of input (e.g. runnable, dataset, model, metadata etc.)
	Kind string `json:"kind,omitempty"`

	// Metadata description
	Metadata *InputParameter `json:"metadata,omitempty"`

	// Input name
	Name string `json:"name,omitempty"`

	// Runnable reference
	Runnable *RunnableRef `json:"runnable,omitempty"`
}

// Validate validates this runnable output
func (m *RunnableOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRunnable(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RunnableOutput) validateMetadata(formats strfmt.Registry) error {
	if swag.IsZero(m.Metadata) { // not required
		return nil
	}

	if m.Metadata != nil {
		if err := m.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *RunnableOutput) validateRunnable(formats strfmt.Registry) error {
	if swag.IsZero(m.Runnable) { // not required
		return nil
	}

	if m.Runnable != nil {
		if err := m.Runnable.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("runnable")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this runnable output based on the context it is used
func (m *RunnableOutput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRunnable(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RunnableOutput) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata != nil {
		if err := m.Metadata.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *RunnableOutput) contextValidateRunnable(ctx context.Context, formats strfmt.Registry) error {

	if m.Runnable != nil {
		if err := m.Runnable.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("runnable")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RunnableOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RunnableOutput) UnmarshalBinary(b []byte) error {
	var res RunnableOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
